<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CellScope.Desktop</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CellScope.Application\CellScope.Application.csproj" />
    <ProjectReference Include="..\CellScope.Domain\CellScope.Domain.csproj" />
    <ProjectReference Include="..\CellScope.Infrastructure\CellScope.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.2" />
  </ItemGroup>
</Project>
